language: python
python:
  - 2.7
install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap-buildout.py -c travis.cfg
  - bin/buildout -Nc travis.cfg
script:
  - bin/code-analysis
  - bin/test
  - bin/createcoverage
after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    - bauer@starzel.de
